# Generated by Django 4.2.1 on 2023-05-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='tltle',
            new_name='title',
        ),
    ]
